services:
  # BACKEND SERVICE
  - type: web
    name: echo-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: uvicorn src.api.main:app --host 0.0.0.0 --port $PORT --app-dir backend
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: GROQ_API_KEY
        sync: false
    plan: free
